<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScamDetector.Core\ScamDetector.Core.csproj" />
  </ItemGroup>

</Project>
